# recommended by travis support:
sudo: required

language: python

python:
  - "2.7"
  - "3.3"

# install dependencies:
install:
  - bash install.sh

# run tests:
script:
  - bash run_tests.sh

# disable email build notifications:
notifications:
  email: false
